version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - static_volume:/app/app/static
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://wildgrill:wildgrillpass@db:5432/wildgrill
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wildgrill
      - POSTGRES_PASSWORD=wildgrillpass
      - POSTGRES_DB=wildgrill
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume: 